/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemasEstrategicosRouteImport } from './routes/temas-estrategicos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReformaTributaria2026RouteImport } from './routes/reforma-tributaria-2026'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as GoianiaRouteImport } from './routes/goiania'
import { Route as EscritorioDeContabilidadeEmGoianiaRouteImport } from './routes/escritorio-de-contabilidade-em-goiania'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContadorEmGoianiaRouteImport } from './routes/contador-em-goiania'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SobreIndexRouteImport } from './routes/sobre.index'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos.index'
import { Route as SolucoesValuationKpisRouteImport } from './routes/solucoes.valuation-kpis'
import { Route as SolucoesTrocarContabilidadeRouteImport } from './routes/solucoes.trocar-contabilidade'
import { Route as SolucoesTecnologiaContabilRouteImport } from './routes/solucoes.tecnologia-contabil'
import { Route as SolucoesSocietarioLegalizacaoRouteImport } from './routes/solucoes.societario-legalizacao'
import { Route as SolucoesRegularizacaoFiscalRouteImport } from './routes/solucoes.regularizacao-fiscal'
import { Route as SolucoesRegistroMarcaInpiRouteImport } from './routes/solucoes.registro-marca-inpi'
import { Route as SolucoesReformaTributariaRouteImport } from './routes/solucoes.reforma-tributaria'
import { Route as SolucoesRecuperacaoCreditosTributariosRouteImport } from './routes/solucoes.recuperacao-creditos-tributarios'
import { Route as SolucoesPlanejamentoTributarioRouteImport } from './routes/solucoes.planejamento-tributario'
import { Route as SolucoesPessoaFisicaIrpfRouteImport } from './routes/solucoes.pessoa-fisica-irpf'
import { Route as SolucoesHoldingPatrimonialRouteImport } from './routes/solucoes.holding-patrimonial'
import { Route as SolucoesDepartamentoPessoalRouteImport } from './routes/solucoes.departamento-pessoal'
import { Route as SolucoesDepartamentoFiscalRouteImport } from './routes/solucoes.departamento-fiscal'
import { Route as SolucoesDefesasFiscaisRouteImport } from './routes/solucoes.defesas-fiscais'
import { Route as SolucoesContabilidadeEmpresarialRouteImport } from './routes/solucoes.contabilidade-empresarial'
import { Route as SolucoesBpoFinanceiroRouteImport } from './routes/solucoes.bpo-financeiro'
import { Route as SolucoesAbrirEmpresaRouteImport } from './routes/solucoes.abrir-empresa'
import { Route as SobreMetodologiaRouteImport } from './routes/sobre.metodologia'
import { Route as SobreLeandroRouteImport } from './routes/sobre.leandro'
import { Route as SegmentosTerceiroSetorRouteImport } from './routes/segmentos.terceiro-setor'
import { Route as SegmentosTecnologiaStartupsRouteImport } from './routes/segmentos.tecnologia-startups'
import { Route as SegmentosSimplesNacionalRouteImport } from './routes/segmentos.simples-nacional'
import { Route as SegmentosProvedoresInternetRouteImport } from './routes/segmentos.provedores-internet'
import { Route as SegmentosProdutorRuralRouteImport } from './routes/segmentos.produtor-rural'
import { Route as SegmentosPrestadoresServicosRouteImport } from './routes/segmentos.prestadores-servicos'
import { Route as SegmentosPendenciasFiscaisRouteImport } from './routes/segmentos.pendencias-fiscais'
import { Route as SegmentosOdontologiaRouteImport } from './routes/segmentos.odontologia'
import { Route as SegmentosMedicosClinicasRouteImport } from './routes/segmentos.medicos-clinicas'
import { Route as SegmentosLucroRealRouteImport } from './routes/segmentos.lucro-real'
import { Route as SegmentosLucroPresumidoRouteImport } from './routes/segmentos.lucro-presumido'
import { Route as SegmentosImobiliariasRouteImport } from './routes/segmentos.imobiliarias'
import { Route as SegmentosHoldingsRouteImport } from './routes/segmentos.holdings'
import { Route as SegmentosFranquiasRedesRouteImport } from './routes/segmentos.franquias-redes'
import { Route as SegmentosEmpresasFamiliaresRouteImport } from './routes/segmentos.empresas-familiares'
import { Route as SegmentosECommerceRouteImport } from './routes/segmentos.e-commerce'
import { Route as SegmentosConstrucaoCivilSpeRouteImport } from './routes/segmentos.construcao-civil-spe'
import { Route as SegmentosCondominiosRouteImport } from './routes/segmentos.condominios'
import { Route as SegmentosComercioRouteImport } from './routes/segmentos.comercio'
import { Route as ConteudosSaudeClinicasRouteImport } from './routes/conteudos.saude-clinicas'
import { Route as ConteudosRespostasValidadasRouteImport } from './routes/conteudos.respostas-validadas'
import { Route as ConteudosRegularizacaoFiscalRouteImport } from './routes/conteudos.regularizacao-fiscal'
import { Route as ConteudosRegimesTributariosRouteImport } from './routes/conteudos.regimes-tributarios'
import { Route as ConteudosPlanejamentoTributarioRouteImport } from './routes/conteudos.planejamento-tributario'
import { Route as ConteudosLc2362026ProcessoAdministrativoFiscalRouteImport } from './routes/conteudos.lc-236-2026-processo-administrativo-fiscal'
import { Route as ConteudosHoldingPatrimonioRouteImport } from './routes/conteudos.holding-patrimonio'
import { Route as ConteudosHoldingFamiliarRouteImport } from './routes/conteudos.holding-familiar'
import { Route as ConteudosGuiaSimplesNacionalRouteImport } from './routes/conteudos.guia-simples-nacional'
import { Route as ConteudosDpEsocialRouteImport } from './routes/conteudos.dp-esocial'
import { Route as ConteudosComercioIcmsRouteImport } from './routes/conteudos.comercio-icms'
import { Route as ConteudosCategoryRouteImport } from './routes/conteudos.$category'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminAuditoriaSeoRouteImport } from './routes/_authenticated/admin.auditoria-seo'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as ApiPublicHooksSeoAuditRunRouteImport } from './routes/api/public/hooks/seo-audit-run'

const TemasEstrategicosRoute = TemasEstrategicosRouteImport.update({
  id: '/temas-estrategicos',
  path: '/temas-estrategicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformaTributaria2026Route = ReformaTributaria2026RouteImport.update({
  id: '/reforma-tributaria-2026',
  path: '/reforma-tributaria-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const GoianiaRoute = GoianiaRouteImport.update({
  id: '/goiania',
  path: '/goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritorioDeContabilidadeEmGoianiaRoute =
  EscritorioDeContabilidadeEmGoianiaRouteImport.update({
    id: '/escritorio-de-contabilidade-em-goiania',
    path: '/escritorio-de-contabilidade-em-goiania',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContadorEmGoianiaRoute = ContadorEmGoianiaRouteImport.update({
  id: '/contador-em-goiania',
  path: '/contador-em-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreIndexRoute = SobreIndexRouteImport.update({
  id: '/sobre/',
  path: '/sobre/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/segmentos/',
  path: '/segmentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesValuationKpisRoute = SolucoesValuationKpisRouteImport.update({
  id: '/solucoes/valuation-kpis',
  path: '/solucoes/valuation-kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesTrocarContabilidadeRoute =
  SolucoesTrocarContabilidadeRouteImport.update({
    id: '/solucoes/trocar-contabilidade',
    path: '/solucoes/trocar-contabilidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesTecnologiaContabilRoute =
  SolucoesTecnologiaContabilRouteImport.update({
    id: '/solucoes/tecnologia-contabil',
    path: '/solucoes/tecnologia-contabil',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesSocietarioLegalizacaoRoute =
  SolucoesSocietarioLegalizacaoRouteImport.update({
    id: '/solucoes/societario-legalizacao',
    path: '/solucoes/societario-legalizacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesRegularizacaoFiscalRoute =
  SolucoesRegularizacaoFiscalRouteImport.update({
    id: '/solucoes/regularizacao-fiscal',
    path: '/solucoes/regularizacao-fiscal',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesRegistroMarcaInpiRoute =
  SolucoesRegistroMarcaInpiRouteImport.update({
    id: '/solucoes/registro-marca-inpi',
    path: '/solucoes/registro-marca-inpi',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesReformaTributariaRoute =
  SolucoesReformaTributariaRouteImport.update({
    id: '/solucoes/reforma-tributaria',
    path: '/solucoes/reforma-tributaria',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesRecuperacaoCreditosTributariosRoute =
  SolucoesRecuperacaoCreditosTributariosRouteImport.update({
    id: '/solucoes/recuperacao-creditos-tributarios',
    path: '/solucoes/recuperacao-creditos-tributarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesPlanejamentoTributarioRoute =
  SolucoesPlanejamentoTributarioRouteImport.update({
    id: '/solucoes/planejamento-tributario',
    path: '/solucoes/planejamento-tributario',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesPessoaFisicaIrpfRoute =
  SolucoesPessoaFisicaIrpfRouteImport.update({
    id: '/solucoes/pessoa-fisica-irpf',
    path: '/solucoes/pessoa-fisica-irpf',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesHoldingPatrimonialRoute =
  SolucoesHoldingPatrimonialRouteImport.update({
    id: '/solucoes/holding-patrimonial',
    path: '/solucoes/holding-patrimonial',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesDepartamentoPessoalRoute =
  SolucoesDepartamentoPessoalRouteImport.update({
    id: '/solucoes/departamento-pessoal',
    path: '/solucoes/departamento-pessoal',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesDepartamentoFiscalRoute =
  SolucoesDepartamentoFiscalRouteImport.update({
    id: '/solucoes/departamento-fiscal',
    path: '/solucoes/departamento-fiscal',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesDefesasFiscaisRoute = SolucoesDefesasFiscaisRouteImport.update({
  id: '/solucoes/defesas-fiscais',
  path: '/solucoes/defesas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesContabilidadeEmpresarialRoute =
  SolucoesContabilidadeEmpresarialRouteImport.update({
    id: '/solucoes/contabilidade-empresarial',
    path: '/solucoes/contabilidade-empresarial',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesBpoFinanceiroRoute = SolucoesBpoFinanceiroRouteImport.update({
  id: '/solucoes/bpo-financeiro',
  path: '/solucoes/bpo-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesAbrirEmpresaRoute = SolucoesAbrirEmpresaRouteImport.update({
  id: '/solucoes/abrir-empresa',
  path: '/solucoes/abrir-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMetodologiaRoute = SobreMetodologiaRouteImport.update({
  id: '/sobre/metodologia',
  path: '/sobre/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreLeandroRoute = SobreLeandroRouteImport.update({
  id: '/sobre/leandro',
  path: '/sobre/leandro',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosTerceiroSetorRoute = SegmentosTerceiroSetorRouteImport.update({
  id: '/segmentos/terceiro-setor',
  path: '/segmentos/terceiro-setor',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosTecnologiaStartupsRoute =
  SegmentosTecnologiaStartupsRouteImport.update({
    id: '/segmentos/tecnologia-startups',
    path: '/segmentos/tecnologia-startups',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosSimplesNacionalRoute =
  SegmentosSimplesNacionalRouteImport.update({
    id: '/segmentos/simples-nacional',
    path: '/segmentos/simples-nacional',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosProvedoresInternetRoute =
  SegmentosProvedoresInternetRouteImport.update({
    id: '/segmentos/provedores-internet',
    path: '/segmentos/provedores-internet',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosProdutorRuralRoute = SegmentosProdutorRuralRouteImport.update({
  id: '/segmentos/produtor-rural',
  path: '/segmentos/produtor-rural',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosPrestadoresServicosRoute =
  SegmentosPrestadoresServicosRouteImport.update({
    id: '/segmentos/prestadores-servicos',
    path: '/segmentos/prestadores-servicos',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosPendenciasFiscaisRoute =
  SegmentosPendenciasFiscaisRouteImport.update({
    id: '/segmentos/pendencias-fiscais',
    path: '/segmentos/pendencias-fiscais',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosOdontologiaRoute = SegmentosOdontologiaRouteImport.update({
  id: '/segmentos/odontologia',
  path: '/segmentos/odontologia',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosMedicosClinicasRoute =
  SegmentosMedicosClinicasRouteImport.update({
    id: '/segmentos/medicos-clinicas',
    path: '/segmentos/medicos-clinicas',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosLucroRealRoute = SegmentosLucroRealRouteImport.update({
  id: '/segmentos/lucro-real',
  path: '/segmentos/lucro-real',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosLucroPresumidoRoute = SegmentosLucroPresumidoRouteImport.update({
  id: '/segmentos/lucro-presumido',
  path: '/segmentos/lucro-presumido',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosImobiliariasRoute = SegmentosImobiliariasRouteImport.update({
  id: '/segmentos/imobiliarias',
  path: '/segmentos/imobiliarias',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosHoldingsRoute = SegmentosHoldingsRouteImport.update({
  id: '/segmentos/holdings',
  path: '/segmentos/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosFranquiasRedesRoute = SegmentosFranquiasRedesRouteImport.update({
  id: '/segmentos/franquias-redes',
  path: '/segmentos/franquias-redes',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosEmpresasFamiliaresRoute =
  SegmentosEmpresasFamiliaresRouteImport.update({
    id: '/segmentos/empresas-familiares',
    path: '/segmentos/empresas-familiares',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosECommerceRoute = SegmentosECommerceRouteImport.update({
  id: '/segmentos/e-commerce',
  path: '/segmentos/e-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosConstrucaoCivilSpeRoute =
  SegmentosConstrucaoCivilSpeRouteImport.update({
    id: '/segmentos/construcao-civil-spe',
    path: '/segmentos/construcao-civil-spe',
    getParentRoute: () => rootRouteImport,
  } as any)
const SegmentosCondominiosRoute = SegmentosCondominiosRouteImport.update({
  id: '/segmentos/condominios',
  path: '/segmentos/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosComercioRoute = SegmentosComercioRouteImport.update({
  id: '/segmentos/comercio',
  path: '/segmentos/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosSaudeClinicasRoute = ConteudosSaudeClinicasRouteImport.update({
  id: '/conteudos/saude-clinicas',
  path: '/conteudos/saude-clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRespostasValidadasRoute =
  ConteudosRespostasValidadasRouteImport.update({
    id: '/conteudos/respostas-validadas',
    path: '/conteudos/respostas-validadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosRegularizacaoFiscalRoute =
  ConteudosRegularizacaoFiscalRouteImport.update({
    id: '/conteudos/regularizacao-fiscal',
    path: '/conteudos/regularizacao-fiscal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosRegimesTributariosRoute =
  ConteudosRegimesTributariosRouteImport.update({
    id: '/conteudos/regimes-tributarios',
    path: '/conteudos/regimes-tributarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosPlanejamentoTributarioRoute =
  ConteudosPlanejamentoTributarioRouteImport.update({
    id: '/conteudos/planejamento-tributario',
    path: '/conteudos/planejamento-tributario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosLc2362026ProcessoAdministrativoFiscalRoute =
  ConteudosLc2362026ProcessoAdministrativoFiscalRouteImport.update({
    id: '/conteudos/lc-236-2026-processo-administrativo-fiscal',
    path: '/conteudos/lc-236-2026-processo-administrativo-fiscal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosHoldingPatrimonioRoute =
  ConteudosHoldingPatrimonioRouteImport.update({
    id: '/conteudos/holding-patrimonio',
    path: '/conteudos/holding-patrimonio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosHoldingFamiliarRoute =
  ConteudosHoldingFamiliarRouteImport.update({
    id: '/conteudos/holding-familiar',
    path: '/conteudos/holding-familiar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosGuiaSimplesNacionalRoute =
  ConteudosGuiaSimplesNacionalRouteImport.update({
    id: '/conteudos/guia-simples-nacional',
    path: '/conteudos/guia-simples-nacional',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudosDpEsocialRoute = ConteudosDpEsocialRouteImport.update({
  id: '/conteudos/dp-esocial',
  path: '/conteudos/dp-esocial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosComercioIcmsRoute = ConteudosComercioIcmsRouteImport.update({
  id: '/conteudos/comercio-icms',
  path: '/conteudos/comercio-icms',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosCategoryRoute = ConteudosCategoryRouteImport.update({
  id: '/conteudos/$category',
  path: '/conteudos/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaSeoRoute =
  AuthenticatedAdminAuditoriaSeoRouteImport.update({
    id: '/admin/auditoria-seo',
    path: '/admin/auditoria-seo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSeoAuditRunRoute =
  ApiPublicHooksSeoAuditRunRouteImport.update({
    id: '/api/public/hooks/seo-audit-run',
    path: '/api/public/hooks/seo-audit-run',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contador-em-goiania': typeof ContadorEmGoianiaRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/escritorio-de-contabilidade-em-goiania': typeof EscritorioDeContabilidadeEmGoianiaRoute
  '/goiania': typeof GoianiaRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reforma-tributaria-2026': typeof ReformaTributaria2026Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temas-estrategicos': typeof TemasEstrategicosRoute
  '/conteudos/$category': typeof ConteudosCategoryRoute
  '/conteudos/comercio-icms': typeof ConteudosComercioIcmsRoute
  '/conteudos/dp-esocial': typeof ConteudosDpEsocialRoute
  '/conteudos/guia-simples-nacional': typeof ConteudosGuiaSimplesNacionalRoute
  '/conteudos/holding-familiar': typeof ConteudosHoldingFamiliarRoute
  '/conteudos/holding-patrimonio': typeof ConteudosHoldingPatrimonioRoute
  '/conteudos/lc-236-2026-processo-administrativo-fiscal': typeof ConteudosLc2362026ProcessoAdministrativoFiscalRoute
  '/conteudos/planejamento-tributario': typeof ConteudosPlanejamentoTributarioRoute
  '/conteudos/regimes-tributarios': typeof ConteudosRegimesTributariosRoute
  '/conteudos/regularizacao-fiscal': typeof ConteudosRegularizacaoFiscalRoute
  '/conteudos/respostas-validadas': typeof ConteudosRespostasValidadasRoute
  '/conteudos/saude-clinicas': typeof ConteudosSaudeClinicasRoute
  '/segmentos/comercio': typeof SegmentosComercioRoute
  '/segmentos/condominios': typeof SegmentosCondominiosRoute
  '/segmentos/construcao-civil-spe': typeof SegmentosConstrucaoCivilSpeRoute
  '/segmentos/e-commerce': typeof SegmentosECommerceRoute
  '/segmentos/empresas-familiares': typeof SegmentosEmpresasFamiliaresRoute
  '/segmentos/franquias-redes': typeof SegmentosFranquiasRedesRoute
  '/segmentos/holdings': typeof SegmentosHoldingsRoute
  '/segmentos/imobiliarias': typeof SegmentosImobiliariasRoute
  '/segmentos/lucro-presumido': typeof SegmentosLucroPresumidoRoute
  '/segmentos/lucro-real': typeof SegmentosLucroRealRoute
  '/segmentos/medicos-clinicas': typeof SegmentosMedicosClinicasRoute
  '/segmentos/odontologia': typeof SegmentosOdontologiaRoute
  '/segmentos/pendencias-fiscais': typeof SegmentosPendenciasFiscaisRoute
  '/segmentos/prestadores-servicos': typeof SegmentosPrestadoresServicosRoute
  '/segmentos/produtor-rural': typeof SegmentosProdutorRuralRoute
  '/segmentos/provedores-internet': typeof SegmentosProvedoresInternetRoute
  '/segmentos/simples-nacional': typeof SegmentosSimplesNacionalRoute
  '/segmentos/tecnologia-startups': typeof SegmentosTecnologiaStartupsRoute
  '/segmentos/terceiro-setor': typeof SegmentosTerceiroSetorRoute
  '/sobre/leandro': typeof SobreLeandroRoute
  '/sobre/metodologia': typeof SobreMetodologiaRoute
  '/solucoes/abrir-empresa': typeof SolucoesAbrirEmpresaRoute
  '/solucoes/bpo-financeiro': typeof SolucoesBpoFinanceiroRoute
  '/solucoes/contabilidade-empresarial': typeof SolucoesContabilidadeEmpresarialRoute
  '/solucoes/defesas-fiscais': typeof SolucoesDefesasFiscaisRoute
  '/solucoes/departamento-fiscal': typeof SolucoesDepartamentoFiscalRoute
  '/solucoes/departamento-pessoal': typeof SolucoesDepartamentoPessoalRoute
  '/solucoes/holding-patrimonial': typeof SolucoesHoldingPatrimonialRoute
  '/solucoes/pessoa-fisica-irpf': typeof SolucoesPessoaFisicaIrpfRoute
  '/solucoes/planejamento-tributario': typeof SolucoesPlanejamentoTributarioRoute
  '/solucoes/recuperacao-creditos-tributarios': typeof SolucoesRecuperacaoCreditosTributariosRoute
  '/solucoes/reforma-tributaria': typeof SolucoesReformaTributariaRoute
  '/solucoes/registro-marca-inpi': typeof SolucoesRegistroMarcaInpiRoute
  '/solucoes/regularizacao-fiscal': typeof SolucoesRegularizacaoFiscalRoute
  '/solucoes/societario-legalizacao': typeof SolucoesSocietarioLegalizacaoRoute
  '/solucoes/tecnologia-contabil': typeof SolucoesTecnologiaContabilRoute
  '/solucoes/trocar-contabilidade': typeof SolucoesTrocarContabilidadeRoute
  '/solucoes/valuation-kpis': typeof SolucoesValuationKpisRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/sobre/': typeof SobreIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/auditoria-seo': typeof AuthenticatedAdminAuditoriaSeoRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/api/public/hooks/seo-audit-run': typeof ApiPublicHooksSeoAuditRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contador-em-goiania': typeof ContadorEmGoianiaRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/escritorio-de-contabilidade-em-goiania': typeof EscritorioDeContabilidadeEmGoianiaRoute
  '/goiania': typeof GoianiaRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reforma-tributaria-2026': typeof ReformaTributaria2026Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temas-estrategicos': typeof TemasEstrategicosRoute
  '/conteudos/$category': typeof ConteudosCategoryRoute
  '/conteudos/comercio-icms': typeof ConteudosComercioIcmsRoute
  '/conteudos/dp-esocial': typeof ConteudosDpEsocialRoute
  '/conteudos/guia-simples-nacional': typeof ConteudosGuiaSimplesNacionalRoute
  '/conteudos/holding-familiar': typeof ConteudosHoldingFamiliarRoute
  '/conteudos/holding-patrimonio': typeof ConteudosHoldingPatrimonioRoute
  '/conteudos/lc-236-2026-processo-administrativo-fiscal': typeof ConteudosLc2362026ProcessoAdministrativoFiscalRoute
  '/conteudos/planejamento-tributario': typeof ConteudosPlanejamentoTributarioRoute
  '/conteudos/regimes-tributarios': typeof ConteudosRegimesTributariosRoute
  '/conteudos/regularizacao-fiscal': typeof ConteudosRegularizacaoFiscalRoute
  '/conteudos/respostas-validadas': typeof ConteudosRespostasValidadasRoute
  '/conteudos/saude-clinicas': typeof ConteudosSaudeClinicasRoute
  '/segmentos/comercio': typeof SegmentosComercioRoute
  '/segmentos/condominios': typeof SegmentosCondominiosRoute
  '/segmentos/construcao-civil-spe': typeof SegmentosConstrucaoCivilSpeRoute
  '/segmentos/e-commerce': typeof SegmentosECommerceRoute
  '/segmentos/empresas-familiares': typeof SegmentosEmpresasFamiliaresRoute
  '/segmentos/franquias-redes': typeof SegmentosFranquiasRedesRoute
  '/segmentos/holdings': typeof SegmentosHoldingsRoute
  '/segmentos/imobiliarias': typeof SegmentosImobiliariasRoute
  '/segmentos/lucro-presumido': typeof SegmentosLucroPresumidoRoute
  '/segmentos/lucro-real': typeof SegmentosLucroRealRoute
  '/segmentos/medicos-clinicas': typeof SegmentosMedicosClinicasRoute
  '/segmentos/odontologia': typeof SegmentosOdontologiaRoute
  '/segmentos/pendencias-fiscais': typeof SegmentosPendenciasFiscaisRoute
  '/segmentos/prestadores-servicos': typeof SegmentosPrestadoresServicosRoute
  '/segmentos/produtor-rural': typeof SegmentosProdutorRuralRoute
  '/segmentos/provedores-internet': typeof SegmentosProvedoresInternetRoute
  '/segmentos/simples-nacional': typeof SegmentosSimplesNacionalRoute
  '/segmentos/tecnologia-startups': typeof SegmentosTecnologiaStartupsRoute
  '/segmentos/terceiro-setor': typeof SegmentosTerceiroSetorRoute
  '/sobre/leandro': typeof SobreLeandroRoute
  '/sobre/metodologia': typeof SobreMetodologiaRoute
  '/solucoes/abrir-empresa': typeof SolucoesAbrirEmpresaRoute
  '/solucoes/bpo-financeiro': typeof SolucoesBpoFinanceiroRoute
  '/solucoes/contabilidade-empresarial': typeof SolucoesContabilidadeEmpresarialRoute
  '/solucoes/defesas-fiscais': typeof SolucoesDefesasFiscaisRoute
  '/solucoes/departamento-fiscal': typeof SolucoesDepartamentoFiscalRoute
  '/solucoes/departamento-pessoal': typeof SolucoesDepartamentoPessoalRoute
  '/solucoes/holding-patrimonial': typeof SolucoesHoldingPatrimonialRoute
  '/solucoes/pessoa-fisica-irpf': typeof SolucoesPessoaFisicaIrpfRoute
  '/solucoes/planejamento-tributario': typeof SolucoesPlanejamentoTributarioRoute
  '/solucoes/recuperacao-creditos-tributarios': typeof SolucoesRecuperacaoCreditosTributariosRoute
  '/solucoes/reforma-tributaria': typeof SolucoesReformaTributariaRoute
  '/solucoes/registro-marca-inpi': typeof SolucoesRegistroMarcaInpiRoute
  '/solucoes/regularizacao-fiscal': typeof SolucoesRegularizacaoFiscalRoute
  '/solucoes/societario-legalizacao': typeof SolucoesSocietarioLegalizacaoRoute
  '/solucoes/tecnologia-contabil': typeof SolucoesTecnologiaContabilRoute
  '/solucoes/trocar-contabilidade': typeof SolucoesTrocarContabilidadeRoute
  '/solucoes/valuation-kpis': typeof SolucoesValuationKpisRoute
  '/conteudos': typeof ConteudosIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/segmentos': typeof SegmentosIndexRoute
  '/sobre': typeof SobreIndexRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/auditoria-seo': typeof AuthenticatedAdminAuditoriaSeoRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/api/public/hooks/seo-audit-run': typeof ApiPublicHooksSeoAuditRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contador-em-goiania': typeof ContadorEmGoianiaRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/escritorio-de-contabilidade-em-goiania': typeof EscritorioDeContabilidadeEmGoianiaRoute
  '/goiania': typeof GoianiaRoute
  '/metodo': typeof MetodoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reforma-tributaria-2026': typeof ReformaTributaria2026Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temas-estrategicos': typeof TemasEstrategicosRoute
  '/conteudos/$category': typeof ConteudosCategoryRoute
  '/conteudos/comercio-icms': typeof ConteudosComercioIcmsRoute
  '/conteudos/dp-esocial': typeof ConteudosDpEsocialRoute
  '/conteudos/guia-simples-nacional': typeof ConteudosGuiaSimplesNacionalRoute
  '/conteudos/holding-familiar': typeof ConteudosHoldingFamiliarRoute
  '/conteudos/holding-patrimonio': typeof ConteudosHoldingPatrimonioRoute
  '/conteudos/lc-236-2026-processo-administrativo-fiscal': typeof ConteudosLc2362026ProcessoAdministrativoFiscalRoute
  '/conteudos/planejamento-tributario': typeof ConteudosPlanejamentoTributarioRoute
  '/conteudos/regimes-tributarios': typeof ConteudosRegimesTributariosRoute
  '/conteudos/regularizacao-fiscal': typeof ConteudosRegularizacaoFiscalRoute
  '/conteudos/respostas-validadas': typeof ConteudosRespostasValidadasRoute
  '/conteudos/saude-clinicas': typeof ConteudosSaudeClinicasRoute
  '/segmentos/comercio': typeof SegmentosComercioRoute
  '/segmentos/condominios': typeof SegmentosCondominiosRoute
  '/segmentos/construcao-civil-spe': typeof SegmentosConstrucaoCivilSpeRoute
  '/segmentos/e-commerce': typeof SegmentosECommerceRoute
  '/segmentos/empresas-familiares': typeof SegmentosEmpresasFamiliaresRoute
  '/segmentos/franquias-redes': typeof SegmentosFranquiasRedesRoute
  '/segmentos/holdings': typeof SegmentosHoldingsRoute
  '/segmentos/imobiliarias': typeof SegmentosImobiliariasRoute
  '/segmentos/lucro-presumido': typeof SegmentosLucroPresumidoRoute
  '/segmentos/lucro-real': typeof SegmentosLucroRealRoute
  '/segmentos/medicos-clinicas': typeof SegmentosMedicosClinicasRoute
  '/segmentos/odontologia': typeof SegmentosOdontologiaRoute
  '/segmentos/pendencias-fiscais': typeof SegmentosPendenciasFiscaisRoute
  '/segmentos/prestadores-servicos': typeof SegmentosPrestadoresServicosRoute
  '/segmentos/produtor-rural': typeof SegmentosProdutorRuralRoute
  '/segmentos/provedores-internet': typeof SegmentosProvedoresInternetRoute
  '/segmentos/simples-nacional': typeof SegmentosSimplesNacionalRoute
  '/segmentos/tecnologia-startups': typeof SegmentosTecnologiaStartupsRoute
  '/segmentos/terceiro-setor': typeof SegmentosTerceiroSetorRoute
  '/sobre/leandro': typeof SobreLeandroRoute
  '/sobre/metodologia': typeof SobreMetodologiaRoute
  '/solucoes/abrir-empresa': typeof SolucoesAbrirEmpresaRoute
  '/solucoes/bpo-financeiro': typeof SolucoesBpoFinanceiroRoute
  '/solucoes/contabilidade-empresarial': typeof SolucoesContabilidadeEmpresarialRoute
  '/solucoes/defesas-fiscais': typeof SolucoesDefesasFiscaisRoute
  '/solucoes/departamento-fiscal': typeof SolucoesDepartamentoFiscalRoute
  '/solucoes/departamento-pessoal': typeof SolucoesDepartamentoPessoalRoute
  '/solucoes/holding-patrimonial': typeof SolucoesHoldingPatrimonialRoute
  '/solucoes/pessoa-fisica-irpf': typeof SolucoesPessoaFisicaIrpfRoute
  '/solucoes/planejamento-tributario': typeof SolucoesPlanejamentoTributarioRoute
  '/solucoes/recuperacao-creditos-tributarios': typeof SolucoesRecuperacaoCreditosTributariosRoute
  '/solucoes/reforma-tributaria': typeof SolucoesReformaTributariaRoute
  '/solucoes/registro-marca-inpi': typeof SolucoesRegistroMarcaInpiRoute
  '/solucoes/regularizacao-fiscal': typeof SolucoesRegularizacaoFiscalRoute
  '/solucoes/societario-legalizacao': typeof SolucoesSocietarioLegalizacaoRoute
  '/solucoes/tecnologia-contabil': typeof SolucoesTecnologiaContabilRoute
  '/solucoes/trocar-contabilidade': typeof SolucoesTrocarContabilidadeRoute
  '/solucoes/valuation-kpis': typeof SolucoesValuationKpisRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/sobre/': typeof SobreIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/auditoria-seo': typeof AuthenticatedAdminAuditoriaSeoRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/api/public/hooks/seo-audit-run': typeof ApiPublicHooksSeoAuditRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contador-em-goiania'
    | '/contato'
    | '/diagnostico'
    | '/escritorio-de-contabilidade-em-goiania'
    | '/goiania'
    | '/metodo'
    | '/privacidade'
    | '/reforma-tributaria-2026'
    | '/sitemap.xml'
    | '/temas-estrategicos'
    | '/conteudos/$category'
    | '/conteudos/comercio-icms'
    | '/conteudos/dp-esocial'
    | '/conteudos/guia-simples-nacional'
    | '/conteudos/holding-familiar'
    | '/conteudos/holding-patrimonio'
    | '/conteudos/lc-236-2026-processo-administrativo-fiscal'
    | '/conteudos/planejamento-tributario'
    | '/conteudos/regimes-tributarios'
    | '/conteudos/regularizacao-fiscal'
    | '/conteudos/respostas-validadas'
    | '/conteudos/saude-clinicas'
    | '/segmentos/comercio'
    | '/segmentos/condominios'
    | '/segmentos/construcao-civil-spe'
    | '/segmentos/e-commerce'
    | '/segmentos/empresas-familiares'
    | '/segmentos/franquias-redes'
    | '/segmentos/holdings'
    | '/segmentos/imobiliarias'
    | '/segmentos/lucro-presumido'
    | '/segmentos/lucro-real'
    | '/segmentos/medicos-clinicas'
    | '/segmentos/odontologia'
    | '/segmentos/pendencias-fiscais'
    | '/segmentos/prestadores-servicos'
    | '/segmentos/produtor-rural'
    | '/segmentos/provedores-internet'
    | '/segmentos/simples-nacional'
    | '/segmentos/tecnologia-startups'
    | '/segmentos/terceiro-setor'
    | '/sobre/leandro'
    | '/sobre/metodologia'
    | '/solucoes/abrir-empresa'
    | '/solucoes/bpo-financeiro'
    | '/solucoes/contabilidade-empresarial'
    | '/solucoes/defesas-fiscais'
    | '/solucoes/departamento-fiscal'
    | '/solucoes/departamento-pessoal'
    | '/solucoes/holding-patrimonial'
    | '/solucoes/pessoa-fisica-irpf'
    | '/solucoes/planejamento-tributario'
    | '/solucoes/recuperacao-creditos-tributarios'
    | '/solucoes/reforma-tributaria'
    | '/solucoes/registro-marca-inpi'
    | '/solucoes/regularizacao-fiscal'
    | '/solucoes/societario-legalizacao'
    | '/solucoes/tecnologia-contabil'
    | '/solucoes/trocar-contabilidade'
    | '/solucoes/valuation-kpis'
    | '/conteudos/'
    | '/insights/'
    | '/segmentos/'
    | '/sobre/'
    | '/solucoes/'
    | '/admin/analytics'
    | '/admin/auditoria-seo'
    | '/admin/leads'
    | '/api/public/hooks/seo-audit-run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contador-em-goiania'
    | '/contato'
    | '/diagnostico'
    | '/escritorio-de-contabilidade-em-goiania'
    | '/goiania'
    | '/metodo'
    | '/privacidade'
    | '/reforma-tributaria-2026'
    | '/sitemap.xml'
    | '/temas-estrategicos'
    | '/conteudos/$category'
    | '/conteudos/comercio-icms'
    | '/conteudos/dp-esocial'
    | '/conteudos/guia-simples-nacional'
    | '/conteudos/holding-familiar'
    | '/conteudos/holding-patrimonio'
    | '/conteudos/lc-236-2026-processo-administrativo-fiscal'
    | '/conteudos/planejamento-tributario'
    | '/conteudos/regimes-tributarios'
    | '/conteudos/regularizacao-fiscal'
    | '/conteudos/respostas-validadas'
    | '/conteudos/saude-clinicas'
    | '/segmentos/comercio'
    | '/segmentos/condominios'
    | '/segmentos/construcao-civil-spe'
    | '/segmentos/e-commerce'
    | '/segmentos/empresas-familiares'
    | '/segmentos/franquias-redes'
    | '/segmentos/holdings'
    | '/segmentos/imobiliarias'
    | '/segmentos/lucro-presumido'
    | '/segmentos/lucro-real'
    | '/segmentos/medicos-clinicas'
    | '/segmentos/odontologia'
    | '/segmentos/pendencias-fiscais'
    | '/segmentos/prestadores-servicos'
    | '/segmentos/produtor-rural'
    | '/segmentos/provedores-internet'
    | '/segmentos/simples-nacional'
    | '/segmentos/tecnologia-startups'
    | '/segmentos/terceiro-setor'
    | '/sobre/leandro'
    | '/sobre/metodologia'
    | '/solucoes/abrir-empresa'
    | '/solucoes/bpo-financeiro'
    | '/solucoes/contabilidade-empresarial'
    | '/solucoes/defesas-fiscais'
    | '/solucoes/departamento-fiscal'
    | '/solucoes/departamento-pessoal'
    | '/solucoes/holding-patrimonial'
    | '/solucoes/pessoa-fisica-irpf'
    | '/solucoes/planejamento-tributario'
    | '/solucoes/recuperacao-creditos-tributarios'
    | '/solucoes/reforma-tributaria'
    | '/solucoes/registro-marca-inpi'
    | '/solucoes/regularizacao-fiscal'
    | '/solucoes/societario-legalizacao'
    | '/solucoes/tecnologia-contabil'
    | '/solucoes/trocar-contabilidade'
    | '/solucoes/valuation-kpis'
    | '/conteudos'
    | '/insights'
    | '/segmentos'
    | '/sobre'
    | '/solucoes'
    | '/admin/analytics'
    | '/admin/auditoria-seo'
    | '/admin/leads'
    | '/api/public/hooks/seo-audit-run'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contador-em-goiania'
    | '/contato'
    | '/diagnostico'
    | '/escritorio-de-contabilidade-em-goiania'
    | '/goiania'
    | '/metodo'
    | '/privacidade'
    | '/reforma-tributaria-2026'
    | '/sitemap.xml'
    | '/temas-estrategicos'
    | '/conteudos/$category'
    | '/conteudos/comercio-icms'
    | '/conteudos/dp-esocial'
    | '/conteudos/guia-simples-nacional'
    | '/conteudos/holding-familiar'
    | '/conteudos/holding-patrimonio'
    | '/conteudos/lc-236-2026-processo-administrativo-fiscal'
    | '/conteudos/planejamento-tributario'
    | '/conteudos/regimes-tributarios'
    | '/conteudos/regularizacao-fiscal'
    | '/conteudos/respostas-validadas'
    | '/conteudos/saude-clinicas'
    | '/segmentos/comercio'
    | '/segmentos/condominios'
    | '/segmentos/construcao-civil-spe'
    | '/segmentos/e-commerce'
    | '/segmentos/empresas-familiares'
    | '/segmentos/franquias-redes'
    | '/segmentos/holdings'
    | '/segmentos/imobiliarias'
    | '/segmentos/lucro-presumido'
    | '/segmentos/lucro-real'
    | '/segmentos/medicos-clinicas'
    | '/segmentos/odontologia'
    | '/segmentos/pendencias-fiscais'
    | '/segmentos/prestadores-servicos'
    | '/segmentos/produtor-rural'
    | '/segmentos/provedores-internet'
    | '/segmentos/simples-nacional'
    | '/segmentos/tecnologia-startups'
    | '/segmentos/terceiro-setor'
    | '/sobre/leandro'
    | '/sobre/metodologia'
    | '/solucoes/abrir-empresa'
    | '/solucoes/bpo-financeiro'
    | '/solucoes/contabilidade-empresarial'
    | '/solucoes/defesas-fiscais'
    | '/solucoes/departamento-fiscal'
    | '/solucoes/departamento-pessoal'
    | '/solucoes/holding-patrimonial'
    | '/solucoes/pessoa-fisica-irpf'
    | '/solucoes/planejamento-tributario'
    | '/solucoes/recuperacao-creditos-tributarios'
    | '/solucoes/reforma-tributaria'
    | '/solucoes/registro-marca-inpi'
    | '/solucoes/regularizacao-fiscal'
    | '/solucoes/societario-legalizacao'
    | '/solucoes/tecnologia-contabil'
    | '/solucoes/trocar-contabilidade'
    | '/solucoes/valuation-kpis'
    | '/conteudos/'
    | '/insights/'
    | '/segmentos/'
    | '/sobre/'
    | '/solucoes/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/auditoria-seo'
    | '/_authenticated/admin/leads'
    | '/api/public/hooks/seo-audit-run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContadorEmGoianiaRoute: typeof ContadorEmGoianiaRoute
  ContatoRoute: typeof ContatoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EscritorioDeContabilidadeEmGoianiaRoute: typeof EscritorioDeContabilidadeEmGoianiaRoute
  GoianiaRoute: typeof GoianiaRoute
  MetodoRoute: typeof MetodoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReformaTributaria2026Route: typeof ReformaTributaria2026Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemasEstrategicosRoute: typeof TemasEstrategicosRoute
  ConteudosCategoryRoute: typeof ConteudosCategoryRoute
  ConteudosComercioIcmsRoute: typeof ConteudosComercioIcmsRoute
  ConteudosDpEsocialRoute: typeof ConteudosDpEsocialRoute
  ConteudosGuiaSimplesNacionalRoute: typeof ConteudosGuiaSimplesNacionalRoute
  ConteudosHoldingFamiliarRoute: typeof ConteudosHoldingFamiliarRoute
  ConteudosHoldingPatrimonioRoute: typeof ConteudosHoldingPatrimonioRoute
  ConteudosLc2362026ProcessoAdministrativoFiscalRoute: typeof ConteudosLc2362026ProcessoAdministrativoFiscalRoute
  ConteudosPlanejamentoTributarioRoute: typeof ConteudosPlanejamentoTributarioRoute
  ConteudosRegimesTributariosRoute: typeof ConteudosRegimesTributariosRoute
  ConteudosRegularizacaoFiscalRoute: typeof ConteudosRegularizacaoFiscalRoute
  ConteudosRespostasValidadasRoute: typeof ConteudosRespostasValidadasRoute
  ConteudosSaudeClinicasRoute: typeof ConteudosSaudeClinicasRoute
  SegmentosComercioRoute: typeof SegmentosComercioRoute
  SegmentosCondominiosRoute: typeof SegmentosCondominiosRoute
  SegmentosConstrucaoCivilSpeRoute: typeof SegmentosConstrucaoCivilSpeRoute
  SegmentosECommerceRoute: typeof SegmentosECommerceRoute
  SegmentosEmpresasFamiliaresRoute: typeof SegmentosEmpresasFamiliaresRoute
  SegmentosFranquiasRedesRoute: typeof SegmentosFranquiasRedesRoute
  SegmentosHoldingsRoute: typeof SegmentosHoldingsRoute
  SegmentosImobiliariasRoute: typeof SegmentosImobiliariasRoute
  SegmentosLucroPresumidoRoute: typeof SegmentosLucroPresumidoRoute
  SegmentosLucroRealRoute: typeof SegmentosLucroRealRoute
  SegmentosMedicosClinicasRoute: typeof SegmentosMedicosClinicasRoute
  SegmentosOdontologiaRoute: typeof SegmentosOdontologiaRoute
  SegmentosPendenciasFiscaisRoute: typeof SegmentosPendenciasFiscaisRoute
  SegmentosPrestadoresServicosRoute: typeof SegmentosPrestadoresServicosRoute
  SegmentosProdutorRuralRoute: typeof SegmentosProdutorRuralRoute
  SegmentosProvedoresInternetRoute: typeof SegmentosProvedoresInternetRoute
  SegmentosSimplesNacionalRoute: typeof SegmentosSimplesNacionalRoute
  SegmentosTecnologiaStartupsRoute: typeof SegmentosTecnologiaStartupsRoute
  SegmentosTerceiroSetorRoute: typeof SegmentosTerceiroSetorRoute
  SobreLeandroRoute: typeof SobreLeandroRoute
  SobreMetodologiaRoute: typeof SobreMetodologiaRoute
  SolucoesAbrirEmpresaRoute: typeof SolucoesAbrirEmpresaRoute
  SolucoesBpoFinanceiroRoute: typeof SolucoesBpoFinanceiroRoute
  SolucoesContabilidadeEmpresarialRoute: typeof SolucoesContabilidadeEmpresarialRoute
  SolucoesDefesasFiscaisRoute: typeof SolucoesDefesasFiscaisRoute
  SolucoesDepartamentoFiscalRoute: typeof SolucoesDepartamentoFiscalRoute
  SolucoesDepartamentoPessoalRoute: typeof SolucoesDepartamentoPessoalRoute
  SolucoesHoldingPatrimonialRoute: typeof SolucoesHoldingPatrimonialRoute
  SolucoesPessoaFisicaIrpfRoute: typeof SolucoesPessoaFisicaIrpfRoute
  SolucoesPlanejamentoTributarioRoute: typeof SolucoesPlanejamentoTributarioRoute
  SolucoesRecuperacaoCreditosTributariosRoute: typeof SolucoesRecuperacaoCreditosTributariosRoute
  SolucoesReformaTributariaRoute: typeof SolucoesReformaTributariaRoute
  SolucoesRegistroMarcaInpiRoute: typeof SolucoesRegistroMarcaInpiRoute
  SolucoesRegularizacaoFiscalRoute: typeof SolucoesRegularizacaoFiscalRoute
  SolucoesSocietarioLegalizacaoRoute: typeof SolucoesSocietarioLegalizacaoRoute
  SolucoesTecnologiaContabilRoute: typeof SolucoesTecnologiaContabilRoute
  SolucoesTrocarContabilidadeRoute: typeof SolucoesTrocarContabilidadeRoute
  SolucoesValuationKpisRoute: typeof SolucoesValuationKpisRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
  SobreIndexRoute: typeof SobreIndexRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
  ApiPublicHooksSeoAuditRunRoute: typeof ApiPublicHooksSeoAuditRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temas-estrategicos': {
      id: '/temas-estrategicos'
      path: '/temas-estrategicos'
      fullPath: '/temas-estrategicos'
      preLoaderRoute: typeof TemasEstrategicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma-tributaria-2026': {
      id: '/reforma-tributaria-2026'
      path: '/reforma-tributaria-2026'
      fullPath: '/reforma-tributaria-2026'
      preLoaderRoute: typeof ReformaTributaria2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goiania': {
      id: '/goiania'
      path: '/goiania'
      fullPath: '/goiania'
      preLoaderRoute: typeof GoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritorio-de-contabilidade-em-goiania': {
      id: '/escritorio-de-contabilidade-em-goiania'
      path: '/escritorio-de-contabilidade-em-goiania'
      fullPath: '/escritorio-de-contabilidade-em-goiania'
      preLoaderRoute: typeof EscritorioDeContabilidadeEmGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contador-em-goiania': {
      id: '/contador-em-goiania'
      path: '/contador-em-goiania'
      fullPath: '/contador-em-goiania'
      preLoaderRoute: typeof ContadorEmGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/': {
      id: '/sobre/'
      path: '/sobre'
      fullPath: '/sobre/'
      preLoaderRoute: typeof SobreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/segmentos'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/valuation-kpis': {
      id: '/solucoes/valuation-kpis'
      path: '/solucoes/valuation-kpis'
      fullPath: '/solucoes/valuation-kpis'
      preLoaderRoute: typeof SolucoesValuationKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/trocar-contabilidade': {
      id: '/solucoes/trocar-contabilidade'
      path: '/solucoes/trocar-contabilidade'
      fullPath: '/solucoes/trocar-contabilidade'
      preLoaderRoute: typeof SolucoesTrocarContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/tecnologia-contabil': {
      id: '/solucoes/tecnologia-contabil'
      path: '/solucoes/tecnologia-contabil'
      fullPath: '/solucoes/tecnologia-contabil'
      preLoaderRoute: typeof SolucoesTecnologiaContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/societario-legalizacao': {
      id: '/solucoes/societario-legalizacao'
      path: '/solucoes/societario-legalizacao'
      fullPath: '/solucoes/societario-legalizacao'
      preLoaderRoute: typeof SolucoesSocietarioLegalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/regularizacao-fiscal': {
      id: '/solucoes/regularizacao-fiscal'
      path: '/solucoes/regularizacao-fiscal'
      fullPath: '/solucoes/regularizacao-fiscal'
      preLoaderRoute: typeof SolucoesRegularizacaoFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/registro-marca-inpi': {
      id: '/solucoes/registro-marca-inpi'
      path: '/solucoes/registro-marca-inpi'
      fullPath: '/solucoes/registro-marca-inpi'
      preLoaderRoute: typeof SolucoesRegistroMarcaInpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/reforma-tributaria': {
      id: '/solucoes/reforma-tributaria'
      path: '/solucoes/reforma-tributaria'
      fullPath: '/solucoes/reforma-tributaria'
      preLoaderRoute: typeof SolucoesReformaTributariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/recuperacao-creditos-tributarios': {
      id: '/solucoes/recuperacao-creditos-tributarios'
      path: '/solucoes/recuperacao-creditos-tributarios'
      fullPath: '/solucoes/recuperacao-creditos-tributarios'
      preLoaderRoute: typeof SolucoesRecuperacaoCreditosTributariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/planejamento-tributario': {
      id: '/solucoes/planejamento-tributario'
      path: '/solucoes/planejamento-tributario'
      fullPath: '/solucoes/planejamento-tributario'
      preLoaderRoute: typeof SolucoesPlanejamentoTributarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/pessoa-fisica-irpf': {
      id: '/solucoes/pessoa-fisica-irpf'
      path: '/solucoes/pessoa-fisica-irpf'
      fullPath: '/solucoes/pessoa-fisica-irpf'
      preLoaderRoute: typeof SolucoesPessoaFisicaIrpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/holding-patrimonial': {
      id: '/solucoes/holding-patrimonial'
      path: '/solucoes/holding-patrimonial'
      fullPath: '/solucoes/holding-patrimonial'
      preLoaderRoute: typeof SolucoesHoldingPatrimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/departamento-pessoal': {
      id: '/solucoes/departamento-pessoal'
      path: '/solucoes/departamento-pessoal'
      fullPath: '/solucoes/departamento-pessoal'
      preLoaderRoute: typeof SolucoesDepartamentoPessoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/departamento-fiscal': {
      id: '/solucoes/departamento-fiscal'
      path: '/solucoes/departamento-fiscal'
      fullPath: '/solucoes/departamento-fiscal'
      preLoaderRoute: typeof SolucoesDepartamentoFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/defesas-fiscais': {
      id: '/solucoes/defesas-fiscais'
      path: '/solucoes/defesas-fiscais'
      fullPath: '/solucoes/defesas-fiscais'
      preLoaderRoute: typeof SolucoesDefesasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/contabilidade-empresarial': {
      id: '/solucoes/contabilidade-empresarial'
      path: '/solucoes/contabilidade-empresarial'
      fullPath: '/solucoes/contabilidade-empresarial'
      preLoaderRoute: typeof SolucoesContabilidadeEmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/bpo-financeiro': {
      id: '/solucoes/bpo-financeiro'
      path: '/solucoes/bpo-financeiro'
      fullPath: '/solucoes/bpo-financeiro'
      preLoaderRoute: typeof SolucoesBpoFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/abrir-empresa': {
      id: '/solucoes/abrir-empresa'
      path: '/solucoes/abrir-empresa'
      fullPath: '/solucoes/abrir-empresa'
      preLoaderRoute: typeof SolucoesAbrirEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/metodologia': {
      id: '/sobre/metodologia'
      path: '/sobre/metodologia'
      fullPath: '/sobre/metodologia'
      preLoaderRoute: typeof SobreMetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/leandro': {
      id: '/sobre/leandro'
      path: '/sobre/leandro'
      fullPath: '/sobre/leandro'
      preLoaderRoute: typeof SobreLeandroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/terceiro-setor': {
      id: '/segmentos/terceiro-setor'
      path: '/segmentos/terceiro-setor'
      fullPath: '/segmentos/terceiro-setor'
      preLoaderRoute: typeof SegmentosTerceiroSetorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/tecnologia-startups': {
      id: '/segmentos/tecnologia-startups'
      path: '/segmentos/tecnologia-startups'
      fullPath: '/segmentos/tecnologia-startups'
      preLoaderRoute: typeof SegmentosTecnologiaStartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/simples-nacional': {
      id: '/segmentos/simples-nacional'
      path: '/segmentos/simples-nacional'
      fullPath: '/segmentos/simples-nacional'
      preLoaderRoute: typeof SegmentosSimplesNacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/provedores-internet': {
      id: '/segmentos/provedores-internet'
      path: '/segmentos/provedores-internet'
      fullPath: '/segmentos/provedores-internet'
      preLoaderRoute: typeof SegmentosProvedoresInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/produtor-rural': {
      id: '/segmentos/produtor-rural'
      path: '/segmentos/produtor-rural'
      fullPath: '/segmentos/produtor-rural'
      preLoaderRoute: typeof SegmentosProdutorRuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/prestadores-servicos': {
      id: '/segmentos/prestadores-servicos'
      path: '/segmentos/prestadores-servicos'
      fullPath: '/segmentos/prestadores-servicos'
      preLoaderRoute: typeof SegmentosPrestadoresServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/pendencias-fiscais': {
      id: '/segmentos/pendencias-fiscais'
      path: '/segmentos/pendencias-fiscais'
      fullPath: '/segmentos/pendencias-fiscais'
      preLoaderRoute: typeof SegmentosPendenciasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/odontologia': {
      id: '/segmentos/odontologia'
      path: '/segmentos/odontologia'
      fullPath: '/segmentos/odontologia'
      preLoaderRoute: typeof SegmentosOdontologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/medicos-clinicas': {
      id: '/segmentos/medicos-clinicas'
      path: '/segmentos/medicos-clinicas'
      fullPath: '/segmentos/medicos-clinicas'
      preLoaderRoute: typeof SegmentosMedicosClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/lucro-real': {
      id: '/segmentos/lucro-real'
      path: '/segmentos/lucro-real'
      fullPath: '/segmentos/lucro-real'
      preLoaderRoute: typeof SegmentosLucroRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/lucro-presumido': {
      id: '/segmentos/lucro-presumido'
      path: '/segmentos/lucro-presumido'
      fullPath: '/segmentos/lucro-presumido'
      preLoaderRoute: typeof SegmentosLucroPresumidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/imobiliarias': {
      id: '/segmentos/imobiliarias'
      path: '/segmentos/imobiliarias'
      fullPath: '/segmentos/imobiliarias'
      preLoaderRoute: typeof SegmentosImobiliariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/holdings': {
      id: '/segmentos/holdings'
      path: '/segmentos/holdings'
      fullPath: '/segmentos/holdings'
      preLoaderRoute: typeof SegmentosHoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/franquias-redes': {
      id: '/segmentos/franquias-redes'
      path: '/segmentos/franquias-redes'
      fullPath: '/segmentos/franquias-redes'
      preLoaderRoute: typeof SegmentosFranquiasRedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/empresas-familiares': {
      id: '/segmentos/empresas-familiares'
      path: '/segmentos/empresas-familiares'
      fullPath: '/segmentos/empresas-familiares'
      preLoaderRoute: typeof SegmentosEmpresasFamiliaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/e-commerce': {
      id: '/segmentos/e-commerce'
      path: '/segmentos/e-commerce'
      fullPath: '/segmentos/e-commerce'
      preLoaderRoute: typeof SegmentosECommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/construcao-civil-spe': {
      id: '/segmentos/construcao-civil-spe'
      path: '/segmentos/construcao-civil-spe'
      fullPath: '/segmentos/construcao-civil-spe'
      preLoaderRoute: typeof SegmentosConstrucaoCivilSpeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/condominios': {
      id: '/segmentos/condominios'
      path: '/segmentos/condominios'
      fullPath: '/segmentos/condominios'
      preLoaderRoute: typeof SegmentosCondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/comercio': {
      id: '/segmentos/comercio'
      path: '/segmentos/comercio'
      fullPath: '/segmentos/comercio'
      preLoaderRoute: typeof SegmentosComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/saude-clinicas': {
      id: '/conteudos/saude-clinicas'
      path: '/conteudos/saude-clinicas'
      fullPath: '/conteudos/saude-clinicas'
      preLoaderRoute: typeof ConteudosSaudeClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/respostas-validadas': {
      id: '/conteudos/respostas-validadas'
      path: '/conteudos/respostas-validadas'
      fullPath: '/conteudos/respostas-validadas'
      preLoaderRoute: typeof ConteudosRespostasValidadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/regularizacao-fiscal': {
      id: '/conteudos/regularizacao-fiscal'
      path: '/conteudos/regularizacao-fiscal'
      fullPath: '/conteudos/regularizacao-fiscal'
      preLoaderRoute: typeof ConteudosRegularizacaoFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/regimes-tributarios': {
      id: '/conteudos/regimes-tributarios'
      path: '/conteudos/regimes-tributarios'
      fullPath: '/conteudos/regimes-tributarios'
      preLoaderRoute: typeof ConteudosRegimesTributariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/planejamento-tributario': {
      id: '/conteudos/planejamento-tributario'
      path: '/conteudos/planejamento-tributario'
      fullPath: '/conteudos/planejamento-tributario'
      preLoaderRoute: typeof ConteudosPlanejamentoTributarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/lc-236-2026-processo-administrativo-fiscal': {
      id: '/conteudos/lc-236-2026-processo-administrativo-fiscal'
      path: '/conteudos/lc-236-2026-processo-administrativo-fiscal'
      fullPath: '/conteudos/lc-236-2026-processo-administrativo-fiscal'
      preLoaderRoute: typeof ConteudosLc2362026ProcessoAdministrativoFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/holding-patrimonio': {
      id: '/conteudos/holding-patrimonio'
      path: '/conteudos/holding-patrimonio'
      fullPath: '/conteudos/holding-patrimonio'
      preLoaderRoute: typeof ConteudosHoldingPatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/holding-familiar': {
      id: '/conteudos/holding-familiar'
      path: '/conteudos/holding-familiar'
      fullPath: '/conteudos/holding-familiar'
      preLoaderRoute: typeof ConteudosHoldingFamiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/guia-simples-nacional': {
      id: '/conteudos/guia-simples-nacional'
      path: '/conteudos/guia-simples-nacional'
      fullPath: '/conteudos/guia-simples-nacional'
      preLoaderRoute: typeof ConteudosGuiaSimplesNacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/dp-esocial': {
      id: '/conteudos/dp-esocial'
      path: '/conteudos/dp-esocial'
      fullPath: '/conteudos/dp-esocial'
      preLoaderRoute: typeof ConteudosDpEsocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/comercio-icms': {
      id: '/conteudos/comercio-icms'
      path: '/conteudos/comercio-icms'
      fullPath: '/conteudos/comercio-icms'
      preLoaderRoute: typeof ConteudosComercioIcmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/$category': {
      id: '/conteudos/$category'
      path: '/conteudos/$category'
      fullPath: '/conteudos/$category'
      preLoaderRoute: typeof ConteudosCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria-seo': {
      id: '/_authenticated/admin/auditoria-seo'
      path: '/admin/auditoria-seo'
      fullPath: '/admin/auditoria-seo'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/seo-audit-run': {
      id: '/api/public/hooks/seo-audit-run'
      path: '/api/public/hooks/seo-audit-run'
      fullPath: '/api/public/hooks/seo-audit-run'
      preLoaderRoute: typeof ApiPublicHooksSeoAuditRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditoriaSeoRoute: typeof AuthenticatedAdminAuditoriaSeoRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditoriaSeoRoute: AuthenticatedAdminAuditoriaSeoRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContadorEmGoianiaRoute: ContadorEmGoianiaRoute,
  ContatoRoute: ContatoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EscritorioDeContabilidadeEmGoianiaRoute:
    EscritorioDeContabilidadeEmGoianiaRoute,
  GoianiaRoute: GoianiaRoute,
  MetodoRoute: MetodoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReformaTributaria2026Route: ReformaTributaria2026Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemasEstrategicosRoute: TemasEstrategicosRoute,
  ConteudosCategoryRoute: ConteudosCategoryRoute,
  ConteudosComercioIcmsRoute: ConteudosComercioIcmsRoute,
  ConteudosDpEsocialRoute: ConteudosDpEsocialRoute,
  ConteudosGuiaSimplesNacionalRoute: ConteudosGuiaSimplesNacionalRoute,
  ConteudosHoldingFamiliarRoute: ConteudosHoldingFamiliarRoute,
  ConteudosHoldingPatrimonioRoute: ConteudosHoldingPatrimonioRoute,
  ConteudosLc2362026ProcessoAdministrativoFiscalRoute:
    ConteudosLc2362026ProcessoAdministrativoFiscalRoute,
  ConteudosPlanejamentoTributarioRoute: ConteudosPlanejamentoTributarioRoute,
  ConteudosRegimesTributariosRoute: ConteudosRegimesTributariosRoute,
  ConteudosRegularizacaoFiscalRoute: ConteudosRegularizacaoFiscalRoute,
  ConteudosRespostasValidadasRoute: ConteudosRespostasValidadasRoute,
  ConteudosSaudeClinicasRoute: ConteudosSaudeClinicasRoute,
  SegmentosComercioRoute: SegmentosComercioRoute,
  SegmentosCondominiosRoute: SegmentosCondominiosRoute,
  SegmentosConstrucaoCivilSpeRoute: SegmentosConstrucaoCivilSpeRoute,
  SegmentosECommerceRoute: SegmentosECommerceRoute,
  SegmentosEmpresasFamiliaresRoute: SegmentosEmpresasFamiliaresRoute,
  SegmentosFranquiasRedesRoute: SegmentosFranquiasRedesRoute,
  SegmentosHoldingsRoute: SegmentosHoldingsRoute,
  SegmentosImobiliariasRoute: SegmentosImobiliariasRoute,
  SegmentosLucroPresumidoRoute: SegmentosLucroPresumidoRoute,
  SegmentosLucroRealRoute: SegmentosLucroRealRoute,
  SegmentosMedicosClinicasRoute: SegmentosMedicosClinicasRoute,
  SegmentosOdontologiaRoute: SegmentosOdontologiaRoute,
  SegmentosPendenciasFiscaisRoute: SegmentosPendenciasFiscaisRoute,
  SegmentosPrestadoresServicosRoute: SegmentosPrestadoresServicosRoute,
  SegmentosProdutorRuralRoute: SegmentosProdutorRuralRoute,
  SegmentosProvedoresInternetRoute: SegmentosProvedoresInternetRoute,
  SegmentosSimplesNacionalRoute: SegmentosSimplesNacionalRoute,
  SegmentosTecnologiaStartupsRoute: SegmentosTecnologiaStartupsRoute,
  SegmentosTerceiroSetorRoute: SegmentosTerceiroSetorRoute,
  SobreLeandroRoute: SobreLeandroRoute,
  SobreMetodologiaRoute: SobreMetodologiaRoute,
  SolucoesAbrirEmpresaRoute: SolucoesAbrirEmpresaRoute,
  SolucoesBpoFinanceiroRoute: SolucoesBpoFinanceiroRoute,
  SolucoesContabilidadeEmpresarialRoute: SolucoesContabilidadeEmpresarialRoute,
  SolucoesDefesasFiscaisRoute: SolucoesDefesasFiscaisRoute,
  SolucoesDepartamentoFiscalRoute: SolucoesDepartamentoFiscalRoute,
  SolucoesDepartamentoPessoalRoute: SolucoesDepartamentoPessoalRoute,
  SolucoesHoldingPatrimonialRoute: SolucoesHoldingPatrimonialRoute,
  SolucoesPessoaFisicaIrpfRoute: SolucoesPessoaFisicaIrpfRoute,
  SolucoesPlanejamentoTributarioRoute: SolucoesPlanejamentoTributarioRoute,
  SolucoesRecuperacaoCreditosTributariosRoute:
    SolucoesRecuperacaoCreditosTributariosRoute,
  SolucoesReformaTributariaRoute: SolucoesReformaTributariaRoute,
  SolucoesRegistroMarcaInpiRoute: SolucoesRegistroMarcaInpiRoute,
  SolucoesRegularizacaoFiscalRoute: SolucoesRegularizacaoFiscalRoute,
  SolucoesSocietarioLegalizacaoRoute: SolucoesSocietarioLegalizacaoRoute,
  SolucoesTecnologiaContabilRoute: SolucoesTecnologiaContabilRoute,
  SolucoesTrocarContabilidadeRoute: SolucoesTrocarContabilidadeRoute,
  SolucoesValuationKpisRoute: SolucoesValuationKpisRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
  SobreIndexRoute: SobreIndexRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
  ApiPublicHooksSeoAuditRunRoute: ApiPublicHooksSeoAuditRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
